services:
  - type: web
    name: aspnet-app
    env: dotnet
    plan: free
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/YourProjectName.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
